# Generated by Django 2.2.3 on 2019-07-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='name',
            field=models.CharField(default='noname', max_length=30),
            preserve_default=False,
        ),
    ]
