# Generated by Django 2.2.3 on 2019-07-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rstie', '0002_poem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='text',
        ),
    ]
